# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OgOd9DRL-0y9B6uGRQMYfmmRPWnq26EU
"""

import streamlit as st
from openai import OpenAI
import traceback

client = OpenAI(api_key="YOUR API")

st.title("📄 AI-Powered Resume Recommendation System")
st.markdown("Paste your resume/profile and the job description to get tailored resume suggestions.")

profile_text = st.text_area("Your Profile", height=150, placeholder="Paste your profile here...")
job_text = st.text_area("Job Description", height=150, placeholder="Paste the job description here...")

if st.button("Generate Recommendation"):
    with st.spinner("Analyzing and generating recommendation..."):
        try:
            prompt = f"""
            You are an AI assistant helping someone choose the best version of their resume.

            User Profile:
            \"\"\"{profile_text}\"\"\"

            Job Description:
            \"\"\"{job_text}\"\"\"

            Provide:
            1. Recommended Resume Type
            2. Matching Skills
            3. Ways to Improve Resume
            4. Explanation
            """

            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "system", "content": "You are a helpful assistant."},
                          {"role": "user", "content": prompt}],
                max_tokens=500,
                temperature=0.7
            )
            result = response.choices[0].message.content.strip()

            st.markdown("### 🧠 Resume Recommendation")
            st.markdown(result)
        except Exception as e:
            st.error("⚠️ Something went wrong. Please check the API key or your input.")
            st.text(traceback.format_exc())

from pyngrok import ngrok

ngrok.set_auth_token("YOUR NGROK TOKEN")

import threading
import time

def run():
    !streamlit run app.py --server.port 8501

thread = threading.Thread(target=run)
thread.start()

time.sleep(5)

public_url = ngrok.connect(addr=8501, proto="http")
print(f"🌐 Your app is live at: {public_url}")